/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GmFootballStandings {
        "competition": string;
        "publicKey": string;
        "season": number;
    }
}
declare global {
    interface HTMLGmFootballStandingsElement extends Components.GmFootballStandings, HTMLStencilElement {
    }
    var HTMLGmFootballStandingsElement: {
        prototype: HTMLGmFootballStandingsElement;
        new (): HTMLGmFootballStandingsElement;
    };
    interface HTMLElementTagNameMap {
        "gm-football-standings": HTMLGmFootballStandingsElement;
    }
}
declare namespace LocalJSX {
    interface GmFootballStandings {
        "competition"?: string;
        "publicKey"?: string;
        "season"?: number;
    }
    interface IntrinsicElements {
        "gm-football-standings": GmFootballStandings;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "gm-football-standings": LocalJSX.GmFootballStandings & JSXBase.HTMLAttributes<HTMLGmFootballStandingsElement>;
        }
    }
}
